name: bit_flasher
description: Send and receive messages using your flash and camera.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  torch_compat: ^1.0.2
  camera: ^0.5.8+7
  provider: ^4.3.2+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
