name: bit_flasher
description: Send and receive messages using your flash and camera.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  torch_compat: ^1.0.2
  camera: ^0.5.8+7
  provider: ^4.3.2+2
  numberpicker: ^1.2.1
  binary: ^2.0.0
  test: ^1.15.4
  characters: ^1.0.0
  collection: ^1.14.13


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
